version: '3'
services:
  postgres:
    image: postgres:11-alpine
    ports:
      - 15433:5432
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=devcurate
      - POSTGRES_DB=coaching
    adminer:
      image: adminer
      ports:
        - 8081:8080
