CREATE DATABASE auth WITH OWNER = postgres ENCODING = 'UTF8' CONNECTION LIMIT = -1;
CREATE DATABASE keys WITH OWNER = postgres ENCODING = 'UTF8' CONNECTION LIMIT = -1;
CREATE DATABASE starter WITH OWNER = postgres ENCODING = 'UTF8' CONNECTION LIMIT = -1;
